- id: '1658686359959'
  alias: LG TV Max volume
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: media_player.lg_tv
    attribute: volume_level
    above: '0.15'
  condition:
  - condition: device
    device_id: 99a48a4c53a65a7fa86e37998866394d
    domain: media_player
    entity_id: media_player.lg_tv
    type: is_on
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    target:
      device_id: 99a48a4c53a65a7fa86e37998866394d
  mode: restart
